version: '3'
services:
  nginx:
    build: ./docker/nginx
    container_name: daas_nginx
    volumes:
      - "./app/backend/drupal:/var/www/html/drupal:rw"
      - "./app/backend/symfony:/var/www/html/symfony:rw"
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
    networks:
      - backend
    #command: [nginx, '-g', 'daemon off;']
    depends_on:
      - database
      - php
      - frontendjs
    links:
      - database
      - php
      - frontendjs


  php:
    build: ./docker/php
    container_name: daas_php
    restart: always
    networks:
      - backend
    volumes:
      - "./app/backend/drupal:/var/www/html/drupal:rw"
      - "./app/backend/symfony:/var/www/html/symfony:rw"


  frontendjs:
    build: ./app/frontend/reactjs
    container_name: daas_fontendjs
    #restart: always
    networks:
      - backend
    volumes:
      - "./app/frontend/reactjs/src:/var/www/html/src:rw"
      - "./app/frontend/reactjs/package.json:/var/www/html/package.json:rw"
      - "./app/frontend/reactjs/webpack.config.js:/var/www/html/webpack.config.js:rw"
    ports:
      - "8080:8080"

  database:
    image: mariadb
    container_name: daas_db
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=daas_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    ports:
      - "3306:3306"


networks:
  backend:
    driver: bridge
